# action.yml
# name: 'Hello World'
# description: 'Greet someone and record the time'
# inputs:
#   who-to-Â²greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.who-to-greet }}
